#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d '1' '2' '3' '4' '5' 

bspc config border_width         4
bspc config window_gap           40
bspc config normal_border_color \#4c566a
bspc config focused_border_color \#4c566a

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xrandr --output DP-4 --mode 1920x1080 --rate 164.97 &
xsetroot -cursor_name left_ptr &
bspc config focus_follows_pointer true &
picom --experimental-backends &
sh ~/.config/polybar//launch.sh &
dunst &
feh --no-fehbg --bg-scale '/home/firefox289/Pictures/Wallpapers/Wallpaper.jpg' 
mpd-discord-rpc
mpd
